---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[curl::default]
      - recipe[java::default]
      #- recipe[tomcat::default]
    attributes:
      java:
        install_flavor: 'oracle'
        oracle:
          accept_oracle_download_terms: 'true'
        jdk_version: '8'
